name: dytty
description: "Voice-first daily journaling app"
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  sqflite: ^2.4.2
  path: ^1.9.1
  path_provider: ^2.1.5
  intl: ^0.20.2
  uuid: ^4.5.1
  speech_to_text: ^7.0.0
  flutter_local_notifications: ^18.0.1
  timezone: ^0.10.0
  permission_handler: ^11.4.0
  provider: ^6.1.4
  table_calendar: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
